FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \    
    iproute2 \
    iputils-ping \
    net-tools \
    tshark \
    tcpdump \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash", "-c", "tail -f /dev/null"]