FROM --platform=linux/amd64 alpine:3.19

RUN apk add --no-cache \
    curl \
    tcpdump \
    net-tools \
    iputils \
    iproute2 \
    bind-tools \
    bash

WORKDIR /workspace

COPY client_setup.sh /usr/local/bin/client_setup.sh
RUN chmod +x /usr/local/bin/client_setup.sh

CMD ["/usr/local/bin/client_setup.sh"]
